
env: dev

db_config:
  db_host: localhost:3306
  url: mysql+mysqlconnector://{0}:{1}@{2}/{3}
  username: uwlight_backend
  password: uwlight12345
  database_name: liight

google_oauth:
  client_id: 180596828410-jkc513n8suqg8u094b73rld5l680let8.apps.googleusercontent.com
  client_secret: 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
  redirect_url: http://127.0.0.1:5001/home

logger:
  app_logger:
    level: DEBUG
    format: "%(asctime)s | %(name)s | %(levelname)s | %(filename)s:%(lineno)s | %(process)d >> %(message)s"
    filename: app.log
  error_logger:
    level: DEBUG
    format: "%(asctime)s | %(name)s | %(levelname)s | %(filename)s:%(lineno)s | %(process)d >> %(message)s"
    filename: error.log
  flask_logger:
    level: DEBUG
    format: "%(asctime)s | %(name)s | %(levelname)s | %(filename)s:%(lineno)s | %(process)d >> %(message)s"
    filename: flask.log

ml_models:
    impressionist_150:
      name: Impressionism
      filename: models/generator_model_impressionist_150.pt
      epoch: 150
      device: mps
      framework: pytorch
      style: Impressionism
      model_class: DCGANGeneratorNet
      show_for_public: True
    impressionist_100:
      name: Impressionism
      filename: models/generator_model_impressionist_100.pt
      epoch: 100
      device: mps
      framework: pytorch
      style: Impressionism
      model_class: DCGANGeneratorNet
      show_for_public: False
    abstract_strip:
      name: Abstract Blocks
      filename: models/generator_model_sngan_genre_100.pt
      epoch: 100
      device: mps
      framework: pytorch
      style: Abstract
      model_class: SNGANGeneratorNet
      show_for_public: True
      dim: 256
    still_lift_300:
      name: Abstract Still-life
      filename: models/generator_model_impressionist_100.pt
      epoch: 300
      device: mps
      framework: pytorch
      style: Still-life
      model_class: DCGANGeneratorNet
      show_for_public: True
    artist_201:
      name: Impressionism
      filename: models/generator_model_artist_201.pt
      epoch: 100
      device: mps
      framework: pytorch
      style: Impressionism
      model_class: DCGANGeneratorNet
      show_for_public: False
    abstract_151:
      name: Impressionism
      filename: models/generator_model_128_151.pt
      epoch: 100
      device: mps
      framework: pytorch
      style: Abstract
      model_class: DCGANGeneratorNet
      show_for_public: False
    autocoder:
      name: Impressionism
      filename: models/encoder.pt
      epoch: 0
      device: cpu
      framework: pytorch
      style: Abstract
      model_class: AE
      show_for_public: False